POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "ThinhTran",
    "password": "thinh1234"
}

###
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "ST",
    "password": "1304440183"
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "ThinhTran",
    "password": "thinh1234"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "ST",
    "password": "1304440183"
}

###
POST http://localhost:5000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTk1MjJhM2ZmYjQ5MGRjODQzOWMxYmUiLCJpYXQiOjE2Mzc5NDk0Njl9.fddmZLF2vZ2wCIeaBFK3Mavf4RxJkH7mkDeXa_9dDjU

{
    "title": "Nodejs",
    "description": "test",
    "url": "google.com",
    "status": "TO LEARN"
}

###
GET http://localhost:5000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTk1MjJhM2ZmYjQ5MGRjODQzOWMxYmUiLCJpYXQiOjE2MzczMTExODV9.6joxIm1i6rxcbCFobqXID-5yHh8arZCSUVUB8Qe-fqQ


###
GET http://localhost:5000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTk3NWRjODQ2OWNmZTU5OWZkMzk1ZTgiLCJpYXQiOjE2MzczMTU5MTZ9.--eXt1pyxEHSN6-nqt12y9zrBBaFYcB9hId606xIrBw

###
PUT http://localhost:5000/api/posts/61975bda771d251585352b7c
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTk3NWRjODQ2OWNmZTU5OWZkMzk1ZTgiLCJpYXQiOjE2MzczMTU4MzF9.NaSm8-HTOS1rqIdqUhP0ULhoF6LJaz4_PtzraFz7J8U

{
    "title": "Reactjs Update",
    "description": "reactjs desc",
    "url": "youtube.com",
    "status": "LEARNED"
}

###
DELETE  http://localhost:5000/api/posts/61975de3469cfe599fd395eb
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTk3NWRjODQ2OWNmZTU5OWZkMzk1ZTgiLCJpYXQiOjE2MzczMTU5MTZ9.--eXt1pyxEHSN6-nqt12y9zrBBaFYcB9hId606xIrBw