POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "ThinhTran",
    "password": "thinh1234"
}

###
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "ST",
    "password": "1304440183"
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "ThinhTran",
    "password": "thinh1234"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "ST",
    "password": "1304440183"
}

###
POST http://localhost:5000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTk3NWRjODQ2OWNmZTU5OWZkMzk1ZTgiLCJpYXQiOjE2MzgwODc3NzJ9.glqU__9IwsD2bfTFPBPMm1io9c90RNrQacsk7gWKmiU

{
    "title": "Reactjs",
    "usernamePost": "test",
    "passwordPost": "123456",
    "url": "google.com",
    "status": "NORMAL"
}

###
GET http://localhost:5000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTk3NWRjODQ2OWNmZTU5OWZkMzk1ZTgiLCJpYXQiOjE2MzgwODc3NzJ9.glqU__9IwsD2bfTFPBPMm1io9c90RNrQacsk7gWKmiU


###
GET http://localhost:5000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTk3NWRjODQ2OWNmZTU5OWZkMzk1ZTgiLCJpYXQiOjE2MzczMTU5MTZ9.--eXt1pyxEHSN6-nqt12y9zrBBaFYcB9hId606xIrBw

###
PUT http://localhost:5000/api/posts/61a33c75ca24ff81fb251b30
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTk3NWRjODQ2OWNmZTU5OWZkMzk1ZTgiLCJpYXQiOjE2MzgwODc3NzJ9.glqU__9IwsD2bfTFPBPMm1io9c90RNrQacsk7gWKmiU

{
    "title": "NodejsED",
    "usernamePost": "test",
    "passwordPost": "123456",
    "url": "google.com",
    "status": "NORMAL"
}

###
DELETE  http://localhost:5000/api/posts/61a33e30ca24ff81fb251b3f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTk3NWRjODQ2OWNmZTU5OWZkMzk1ZTgiLCJpYXQiOjE2MzgwODc3NzJ9.glqU__9IwsD2bfTFPBPMm1io9c90RNrQacsk7gWKmiU